### ISSUE TITLE
Various Tweaks

### ISSUE THREAD

**Issue by jpotvin** [Xalgorithms/rm-functions#3]
1. The subtitles "Character of this Obligation" etc, should be one font size larger and bold.
2. Adjust the "Qualitative Weights" subtitle to "Output: Qualitative Weights"
3. Remove "There are" from each label of the 2nd group of Qualitative Weights. 
4. Move "Select the rule category that most applies." to an "Output: Purpose" Section immediately before "Output: Qualitative Weights"
5. Adjust each of the "Input" subtitles to have a colon like:  "Input: Contexts" 
6. I'm considering a whole section for "Output" fields and a whole section of "Input" fields. But for clarity it doesn't hurt to remind the author with word repetition which aspect they are working on. So we can leave it as is I think. 
7. For "Involved Party" please line-break to drop "Standard Industry Code" beneath.
8. For "Involved Product or Service" also line-break to drop "Standard Product or Service Code" beneath (note, do not repeat "Standard Industry Code"); also change "Add Involved Party" to "Add Involved Product or Service"
9. Reminder to put the correct choices into the <grin>No Peace; No Justice</grin> lists.
10. Move the "Save Rule Information" button to be quite visible inside the left-side panel, to be hit anytime for interim saving.

...that's enough for one list of tweaks. I'll put others into a separate entry.

**Comment by RyanFleck** [comment]
Good feedback. We'll probably be able to address most of these in one fell swoop. Two issues:

> Reminder to put the correct choices into the No Peace; No Justice lists.

What would you like these to be? We can do a first draft.

> Move the "Save Rule Information" button to be quite visible inside the left-side panel, to be hit anytime for interim saving.

We can't do this for technical reasons: each component monitors its own fields, so saving must be included at the section level.

## ToDo:

- [ ] The subtitles "Character of this Obligation" etc, should be one font size larger and bold.
- [ ] Adjust the "Qualitative Weights" subtitle to "Output: Qualitative Weights"
- [ ] Remove "There are" from each label of the 2nd group of Qualitative Weights.
- [ ] Move "Select the rule category that most applies." to an "Output: Purpose" Section immediately before "Output: Qualitative Weights"
- [ ] Adjust each of the "Input" subtitles to have a colon like: "Input: Contexts"
- [ ] For "Involved Party" please line-break to drop "Standard Industry Code" beneath.
- [ ] For "Involved Product or Service" also line-break to drop "Standard Product or Service Code" beneath (note, do not repeat "Standard Industry Code"); also change "Add Involved Party" to "Add Involved Product or Service"
